/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package addressbookapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author siane
 */
public class AddressBookGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddressBookGUI.class.getName());

    /**
     * Creates new form AddressBookGUI
     */
    //variables
    protected String fName, sName, email, phone, address;
    
    //Declare our ArrayList
    ArrayList<AddressBook> contacts = new ArrayList<AddressBook>();
    
    //I/O Stream
    //save method
    private void save(){
        File f;
        FileOutputStream fos;
        ObjectOutputStream oos;
        try{
            f = new File("contactList.txt");
            fos = new FileOutputStream(f);
            oos = new ObjectOutputStream(fos);
            
            oos.writeObject(contacts); //writing the array list to the file
            oos.close(); //close it
            System.out.println("Saved to file");
       }catch(IOException e){
            System.out.println("Exception saving to file "+e);
        }
    }
    
    //load method
     private void load(){
        File f;
        FileInputStream fis;
        ObjectInputStream ois;
        try{
            f = new File("contactList.txt");
            fis = new FileInputStream(f);
            ois = new ObjectInputStream(fis);
            
            contacts = (ArrayList<AddressBook>)ois.readObject(); //cast it to User obj in ArrayList
            ois.close();
            displayTA.append("");
        }catch(IOException | ClassNotFoundException e){
            System.out.println("Loading file error " +e);
        }
    }
    
    public AddressBookGUI() {
        initComponents();
        //my load method
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        fNameLBL = new javax.swing.JLabel();
        sNameLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        addressLBL = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        sNameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setText("Address Book App");

        fNameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fNameLBL.setText("First Name:");

        sNameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sNameLBL.setText("Surname:");

        emailLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLBL.setText("Email Address:");

        phoneLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phoneLBL.setText("Phone Number:");

        addressLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressLBL.setText("Address:");

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(this::addBTNActionPerformed);

        displayBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(this::displayBTNActionPerformed);

        searchBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(this::searchBTNActionPerformed);

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(this::deleteBTNActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameLBL)
                            .addComponent(sNameLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(phoneLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(phoneTF))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(emailLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(titleLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addressLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(addBTN)
                        .addGap(53, 53, 53)
                        .addComponent(displayBTN)
                        .addGap(59, 59, 59)
                        .addComponent(searchBTN)
                        .addGap(56, 56, 56)
                        .addComponent(deleteBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLBL)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameLBL)
                            .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sNameLBL)
                            .addComponent(sNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLBL)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLBL)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLBL)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(displayBTN)
                    .addComponent(searchBTN)
                    .addComponent(deleteBTN))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
         fName = fNameTF.getText();
        sName = sNameTF.getText();
        email = emailTF.getText();
        phone = phoneTF.getText();
        address = addressTF.getText();
        
        boolean exists = false;
        
        // Check for empty fields
        if (fName.isEmpty() || sName.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter a first name, a last name and a phone number");
            return;
        }

    for (AddressBook con : contacts) {
        if (con.getfName().equals(fName)
            && con.getsName().equals(sName)
            && con.getEmail().equals(email)
            && con.getPhone().equals(phone)
            && con.getAddress().equals(address)) {
            exists = true;
            break;
        }
    }

    if (exists) {
    JOptionPane.showMessageDialog(null, "That contact already exists in your phone book");
    } else {
    AddressBook tempS = new AddressBook(fName,sName,email,phone,address);
    contacts.add(tempS);
    JOptionPane.showMessageDialog(null, "Contact added!");
    }
    
    save();
    
    fNameTF.setText("");
    sNameTF.setText("");
    emailTF.setText("");
    phoneTF.setText("");
    addressTF.setText("");

    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        fName = fNameTF.getText();
        sName = sNameTF.getText();
        email = emailTF.getText();
        phone = phoneTF.getText();
        address = addressTF.getText();
        
        //Set the text to what is in the ArrayList
        StringBuffer sBuff = new StringBuffer();
        for (AddressBook con: contacts) {
            sBuff.append(con.toString());
            sBuff.append("\n");
        }
        
        String allContacts = sBuff.toString();
        displayTA.setText(allContacts);
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        fName = fNameTF.getText();
        sName = sNameTF.getText();
        email = emailTF.getText();
        phone = phoneTF.getText();
        address = addressTF.getText();
        
        //Make sure at least one field is filled in
        if(phone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a phone number");
        }
        
        //If Statement
        for (AddressBook con : contacts) {
            if (con.getPhone().equals(phone)) {
                displayTA.setText(con.toString());
                return;
            }
        }

        displayTA.setText("No matching contact found");
        
        fNameTF.setText("");
        sNameTF.setText("");
        emailTF.setText("");
        phoneTF.setText("");
        addressTF.setText("");

    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        fName = fNameTF.getText();
        sName = sNameTF.getText();
        email = emailTF.getText();
        phone = phoneTF.getText().trim();
        address = addressTF.getText();
        
        //Make sure every field is filled in
        if(phone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a phone number to delete");
            return;
        }
        
        //If Statement
        AddressBook toDelete = null;

        for (AddressBook con : contacts) {
            if (con.getPhone().equals(phone)) {
                toDelete = con;
                break;
            }
        }

        if (toDelete != null) {
            contacts.remove(toDelete);
            JOptionPane.showMessageDialog(null, "Contact deleted!");
        } else {
            JOptionPane.showMessageDialog(null, "No match found");
        }
        
        save();
        
        fNameTF.setText("");
        sNameTF.setText("");
        emailTF.setText("");
        phoneTF.setText("");
        addressTF.setText("");

    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddressBookGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addressLBL;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel fNameLBL;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel sNameLBL;
    private javax.swing.JTextField sNameTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
